nodes = [
    {"name": "元春"},
    {"name": "凤姐"},
    {"name": "妙玉"},
    {"name": "宝玉"},
    {"name": "宝琴"},
    {"name": "宝钗"},
    {"name": "惜春"},
    {"name": "探春"},
    {"name": "李纨"},
    {"name": "李纹"},
    {"name": "李绮"},
    {"name": "湘云"},
    {"name": "癞头僧"},
    {"name": "贾兰"},
    {"name": "贾环"},
    {"name": "迎春"},
    {"name": "邢岫烟"},
    {"name": "香菱"},
    {"name": "香菱 "},
    {"name": "黛玉"},
    {"name": "凹晶馆"},
    {"name": "怡红院"},
    {"name": "暖香坞"},
    {"name": "栊翠庵"},
    {"name": "潇湘馆"},
    {"name": "秋爽斋"},
    {"name": "稻香村"},
    {"name": "紫菱洲"},
    {"name": "芦雪庵"},
    {"name": "葬花冢"},
    {"name": "藕香榭"},
    {"name": "贾政书房"},
    {"name": "贾母上房"},
    {"name": "贾母正室"},
    {"name": "中秋即景联诗"},
    {"name": "元妃省亲题匾额"},
    {"name": "元妃集谜语诗"},
    {"name": "咏玉"},
    {"name": "咏红梅"},
    {"name": "宝玉独吟 2"},
    {"name": "宝玉独吟 3"},
    {"name": "宝玉独吟 4"},
    {"name": "宝玉独咏"},
    {"name": "宝黛论偈语"},
    {"name": "桃花社柳絮词"},
    {"name": "海棠诗社"},
    {"name": "芦雪庵联句"},
    {"name": "薛宝琴独咏"},
    {"name": "观中秋即景联诗"},
    {"name": "论庄子"},
    {"name": "谜语诗"},
    {"name": "贾政试才姽婳词"},
    {"name": "贾政试才题对联"},
    {"name": "赏菊咏蟹 1"},
    {"name": "赏菊咏蟹 2"},
    {"name": "香菱独咏"},
    {"name": "黛玉独咏 1"},
    {"name": "黛玉独咏 2"},
    {"name": "黛玉独咏 3"},
    {"name": "黛玉独咏 4"},
    {"name": "黛玉独咏 5"}

]
# nodes需要把桑基图中出现的名称全部设置进去，并且要保证links中的名称与name相同
links = [
    {"source": "元春", "target": "元妃省亲题匾额", "value": 1},
    {"source": "元春", "target": "元妃集谜语诗", "value": 1},
    {"source": "凤姐", "target": "芦雪庵联句", "value": 1},
    {"source": "妙玉", "target": "观中秋即景联诗", "value": 1},
    {"source": "宝玉", "target": "元妃省亲题匾额", "value": 3},
    {"source": "宝玉", "target": "咏红梅", "value": 1},
    {"source": "宝玉", "target": "宝玉独吟 2", "value": 4},
    {"source": "宝玉", "target": "宝玉独吟 3", "value": 1},
    {"source": "宝玉", "target": "宝玉独吟 4", "value": 1},
    {"source": "宝玉", "target": "宝玉独咏", "value": 1},
    {"source": "宝玉", "target": "宝黛论偈语", "value": 1},
    {"source": "宝玉", "target": "桃花社柳絮词", "value": 1},
    {"source": "宝玉", "target": "海棠诗社", "value": 1},
    {"source": "宝玉", "target": "芦雪庵联句", "value": 2},
    {"source": "宝玉", "target": "论庄子", "value": 1},
    {"source": "宝玉", "target": "谜语诗", "value": 1},
    {"source": "宝玉", "target": "贾政试才姽婳词", "value": 1},
    {"source": "宝玉", "target": "贾政试才题对联", "value": 4},
    {"source": "宝玉", "target": "赏菊咏蟹 1", "value": 2},
    {"source": "宝玉", "target": "赏菊咏蟹 2", "value": 1},
    {"source": "宝琴", "target": "咏红梅", "value": 1},
    {"source": "宝琴", "target": "桃花社柳絮词", "value": 1},
    {"source": "宝琴", "target": "芦雪庵联句", "value": 9},
    {"source": "宝琴", "target": "薛宝琴独咏", "value": 10},
    {"source": "宝钗", "target": "元妃省亲题匾额", "value": 1},
    {"source": "宝钗", "target": "元妃集谜语诗", "value": 1},
    {"source": "宝钗", "target": "桃花社柳絮词", "value": 1},
    {"source": "宝钗", "target": "海棠诗社", "value": 1},
    {"source": "宝钗", "target": "芦雪庵联句", "value": 3},
    {"source": "宝钗", "target": "谜语诗", "value": 1},
    {"source": "宝钗", "target": "赏菊咏蟹 1", "value": 2},
    {"source": "宝钗", "target": "赏菊咏蟹 2", "value": 1},
    {"source": "惜春", "target": "元妃省亲题匾额", "value": 1},
    {"source": "惜春", "target": "元妃集谜语诗", "value": 1},
    {"source": "探春", "target": "元妃省亲题匾额", "value": 1},
    {"source": "探春", "target": "元妃集谜语诗", "value": 1},
    {"source": "探春", "target": "桃花社柳絮词", "value": 1},
    {"source": "探春", "target": "海棠诗社", "value": 2},
    {"source": "探春", "target": "芦雪庵联句", "value": 2},
    {"source": "探春", "target": "赏菊咏蟹 1", "value": 2},
    {"source": "李纨", "target": "元妃省亲题匾额", "value": 1},
    {"source": "李纨", "target": "芦雪庵联句", "value": 3},
    {"source": "李纹", "target": "咏红梅", "value": 1},
    {"source": "李纹", "target": "芦雪庵联句", "value": 1},
    {"source": "李绮", "target": "芦雪庵联句", "value": 2},
    {"source": "湘云", "target": "中秋即景联诗", "value": 11},
    {"source": "湘云", "target": "桃花社柳絮词", "value": 1},
    {"source": "湘云", "target": "海棠诗社", "value": 2},
    {"source": "湘云", "target": "芦雪庵联句", "value": 12},
    {"source": "湘云", "target": "谜语诗", "value": 1},
    {"source": "湘云", "target": "赏菊咏蟹 1", "value": 3},
    {"source": "癞头僧", "target": "咏玉", "value": 2},
    {"source": "贾兰", "target": "贾政试才姽婳词", "value": 1},
    {"source": "贾环", "target": "元妃集谜语诗", "value": 1},
    {"source": "贾环", "target": "贾政试才姽婳词", "value": 1},
    {"source": "迎春", "target": "元妃省亲题匾额", "value": 1},
    {"source": "迎春", "target": "元妃集谜语诗", "value": 1},
    {"source": "邢岫烟", "target": "咏红梅", "value": 1},
    {"source": "邢岫烟", "target": "芦雪庵联句", "value": 2},
    {"source": "香菱", "target": "芦雪庵联句", "value": 1},
    {"source": "香菱 ", "target": "香菱独咏", "value": 2},
    {"source": "黛玉", "target": "中秋即景联诗", "value": 12},
    {"source": "黛玉", "target": "元妃省亲题匾额", "value": 2},
    {"source": "黛玉", "target": "宝黛论偈语", "value": 1},
    {"source": "黛玉", "target": "桃花社柳絮词", "value": 1},
    {"source": "黛玉", "target": "海棠诗社", "value": 1},
    {"source": "黛玉", "target": "芦雪庵联句", "value": 8},
    {"source": "黛玉", "target": "论庄子", "value": 1},
    {"source": "黛玉", "target": "谜语诗", "value": 1},
    {"source": "黛玉", "target": "赏菊咏蟹 1", "value": 2},
    {"source": "黛玉", "target": "赏菊咏蟹 2", "value": 2},
    {"source": "黛玉", "target": "黛玉独咏 1", "value": 1},
    {"source": "黛玉", "target": "黛玉独咏 2", "value": 1},
    {"source": "黛玉", "target": "黛玉独咏 3", "value": 1},
    {"source": "黛玉", "target": "黛玉独咏 4", "value": 5},
    {"source": "黛玉", "target": "黛玉独咏 5", "value": 1},

    {"source": "中秋即景联诗", "target": "凹晶馆", "value": 23},
    {"source": "元妃省亲题匾额", "target": "贾母正室", "value": 11},
    {"source": "元妃集谜语诗", "target": "贾母上房", "value": 5},
    {"source": "元妃集谜语诗", "target": "贾母正室", "value": 1},
    {"source": "咏玉", "target": "怡红院", "value": 2},
    {"source": "咏红梅", "target": "芦雪庵", "value": 4},
    {"source": "宝玉独吟 2", "target": "怡红院", "value": 4},
    {"source": "宝玉独吟 3", "target": "贾政书房", "value": 1},
    {"source": "宝玉独吟 4", "target": "紫菱洲", "value": 1},
    {"source": "宝玉独咏", "target": "怡红院", "value": 1},
    {"source": "宝黛论偈语", "target": "怡红院", "value": 2},
    {"source": "桃花社柳絮词", "target": "潇湘馆", "value": 6},
    {"source": "海棠诗社", "target": "秋爽斋", "value": 7},
    {"source": "芦雪庵联句", "target": "芦雪庵", "value": 46},
    {"source": "薛宝琴独咏", "target": "暖香坞", "value": 10},
    {"source": "观中秋即景联诗", "target": "栊翠庵", "value": 1},
    {"source": "论庄子", "target": "怡红院", "value": 2},
    {"source": "谜语诗", "target": "暖香坞", "value": 3},
    {"source": "谜语诗", "target": "潇湘馆", "value": 1},
    {"source": "贾政试才姽婳词", "target": "怡红院", "value": 1},
    {"source": "贾政试才姽婳词", "target": "贾政书房", "value": 2},
    {"source": "贾政试才题对联", "target": "稻香村", "value": 4},
    {"source": "赏菊咏蟹 1", "target": "秋爽斋", "value": 5},
    {"source": "赏菊咏蟹 1", "target": "藕香榭", "value": 6},
    {"source": "赏菊咏蟹 2", "target": "藕香榭", "value": 4},
    {"source": "香菱独咏", "target": "潇湘馆", "value": 2},
    {"source": "黛玉独咏 1", "target": "葬花冢", "value": 1},
    {"source": "黛玉独咏 2", "target": "潇湘馆", "value": 1},
    {"source": "黛玉独咏 3", "target": "潇湘馆", "value": 1},
    {"source": "黛玉独咏 4", "target": "潇湘馆", "value": 5},
    {"source": "黛玉独咏 5", "target": "潇湘馆", "value": 1}
]
# links代表节点关系，source表示起点，target表示终点，需要将节点关系全部输入进去，value表示节点长度
from pyecharts import Sankey

sankey = Sankey("名称", width=1600, height=900)  # 可以设置大小和图标名称
# sankey.use_theme('dark') 	#图表主题，pyecharts可以自定义主题，‘dark’可以显示为黑色背景。
sankey.add(
    '按钮',  # 按钮，用来控制是否显示图标。若不显示，可以设置为‘空格’
    nodes,  # 输入节点，如果导入json数据，nodes=json['nodes]
    links,  # 输入关系,nodes=json['links']
    line_opacity=0.6,  # 曲线色彩深度
    line_curve=0.6,  # 曲线弧度
    line_color="target",  # 以target为自动选择颜色的基准，也可以设置为source
    line_width=3,  # 曲线宽度
    is_label_show=True,  # 是否显示标签，默认值为True
    label_text_size=16,  # 设置标签字体大小
    label_pos="right",  # 标签位置，可以设置靠左或靠右
    label_color='颜色',  # 设置标签颜色
    is_random=True,  # 曲线颜色随机排列
    sankey_node_gap=20,  # 桑基图同列上下节点之间的距离，如果做图时字体太密，可以调整一下节点距离。
)
sankey.render()
